import { View } from "@/components/ui/view";
import { useLocalSearchParams, useNavigation } from "expo-router";
import { useEffect, useState } from "react";

// New conversation template
const DefaultConversation: Conversation = {
    courseId: '123456',
    conversationId: null,
    activeRunId: null,
    title: 'New Conversation',
    messages: [],
    updatedAt: new Date().toISOString()
};

const FakeOldConversations: Conversation = {
    courseId: '123456',
    conversationId: 'UUID',
    activeRunId: null,
    title: 'Old Conversation',
    messages: [],
    updatedAt: new Date().toISOString()
};

// For simplicity, we are using the same Conversation interface for both old and new conversations.
export interface Conversation {
    courseId: string;
    conversationId: string | null; //null = first time
    activeRunId: string | null; //null = not started
    title: string; // default: 'New Conversation'
    messages: (UserMessage | AssistantMessage)[];
    updatedAt: string; // ISO string
}

// RunStatus represents the lifecycle of an assistant message generation process,
// from the moment it's initiated (PENDING) to its completion (DONE) or failure (ERROR).
export type RunStatus = 'PENDING' | 'THINKING' | 'STREAMING' | 'DONE' | 'ERROR' | 'CANCELLED' | 'STALE';

// UserMsgStatus represents the various states a user message can be in,
// from its initial creation (DRAFT) to its successful sending (SENT) or failure (FAILED).
export type UserMsgStatus = 'DRAFT' | 'SENDING' | 'SENT' | 'FAILED' | 'REJECTED_RUN_IN_PROGRESS' | 'DUPLICATE';

// UserMessage represents a message sent by the user, including its content,
// status, and metadata such as timestamps and error information if sending fails.
export interface UserMessage {
    clientMessageId: string;
    role: 'user';
    content: string;
    createdAt: string;
    messageIdLocal: number;
    conversationId: string | null; // null = first time
    status: UserMsgStatus;
    sendAttemptCount: number;
    lastError?: AppError | null;
}

// AssistantMessage represents a message generated by the assistant, including its content,
// generation status, and metadata such as timestamps and error information if generation fails.
export interface AssistantMessage {
    role: 'assistant';
    runId: string;
    content: string;
    messageIdLocal: number;
    conversationId: string;
    status: RunStatus;
    startedAt: string | null; // null = PENDING
    finishedAt: string | null; // null = STREAMING or earlier
    firstTokenAt: string | null; //null = THINKING or earlier
    lastEventId: string | null; // null = PENDING
    error?: AppError | null;
}

// AppError is a standardized error format used across the application to represent errors in a consistent way.
type AppError = {
    code?: string;        // e.g. RUN_IN_PROGRESS, NETWORK_ERROR
    message: string;
    detail?: unknown;     // raw error payload
    httpStatus?: number;
    retryable?: boolean;
};

/**
 * ConversationScreen is the main screen for displaying a conversation between a user and an assistant.
 * It retrieves the courseId and conversationId from the URL parameters and displays them.
 * If conversationId is not provided, it defaults to 'new', indicating a new conversation.
 * @constructor
 */
export default function ConversationScreen() {
    const {courseId, conversationId} = useLocalSearchParams<{
        courseId: string;
        conversationId?: string;
    }>();
    const navigation = useNavigation();
    const [conversation, setConversation] = useState<Conversation | null>(null)

    // Fetch conversation data when the component mounts or when courseId/conversationId changes.
    useEffect(() => {
        //TODO: fetch conversation by conversationId, if conversationId is null, use DefaultConversation

        setTimeout(() => {
            if ( conversationId ) {
                // Simulate fetching an existing conversation
                setConversation({...FakeOldConversations, conversationId, courseId});
            } else {
                setConversation({...DefaultConversation, conversationId: null, courseId});
            }
        }, 1000);
    }, [conversationId, courseId]);

    // Update the screen title based on the conversation title.
    useEffect(() => {
        if ( !conversation?.title ) return;
        navigation.setOptions({title: conversation.title});
    }, [conversation?.title, navigation]);

    return (
        <View>

        </View>
    );
}
